@ sub_080DBEB4, verbatim from the base ROM at 0x080dbeb4 (32 bytes).
@ Generated by tools/make_permuter_dir.py. Verify with tools/permuter_setup.sh.
@ prelude.inc is MIPS-only and is deliberately not included.

	.text
	.syntax unified
	.thumb
	.align 2, 0
	.globl sub_080DBEB4
	.type sub_080DBEB4, %function
	.thumb_func
sub_080DBEB4:
	push	{lr}
	adds	r2, r0, #0
	lsls	r1, r1, #0x18
	cmp	r1, #0
	beq	.L0
	ldr	r0, [r2, #0x30]
	movs	r1, #2
	rsbs	r1, r1, #0
	ands	r0, r1
	b	.L1
.L0:
	ldr	r0, [r2, #0x30]
	movs	r1, #1
	orrs	r0, r1
.L1:
	str	r0, [r2, #0x30]
	pop	{r0}
	bx	r0
	.size	sub_080DBEB4, . - sub_080DBEB4
