@ sub_0801AD1C, verbatim from the base ROM at 0x0801ad1c (28 bytes).
@ Generated by tools/make_permuter_dir.py. Verify with tools/permuter_setup.sh.
@ prelude.inc is MIPS-only and is deliberately not included.

	.text
	.syntax unified
	.thumb
	.align 2, 0
	.globl sub_0801AD1C
	.type sub_0801AD1C, %function
	.thumb_func
sub_0801AD1C:
	push	{lr}
	lsls	r0, r0, #0x18
	ldr	r1, [pc, #0x10]
	cmp	r0, #0
	beq	.L0
	movs	r0, #0x80
	lsls	r0, r0, #6
	adds	r1, r1, r0
.L0:
	adds	r0, r1, #0
	pop	{r1}
	bx	r1
	movs	r0, r0
	str	r1, [sp, #0x280]
	lsls	r0, r0, #8
	.size	sub_0801AD1C, . - sub_0801AD1C
