@ sub_0804E014, verbatim from the base ROM at 0x0804e014 (28 bytes).
@ Generated by tools/make_permuter_dir.py. Verify with tools/permuter_setup.sh.
@ prelude.inc is MIPS-only and is deliberately not included.

	.text
	.syntax unified
	.thumb
	.align 2, 0
	.globl sub_0804E014
	.type sub_0804E014, %function
	.thumb_func
sub_0804E014:
	push	{lr}
	lsls	r0, r0, #0x18
	ldr	r1, [pc, #8]
	ldr	r1, [r1, #0xc]
	cmp	r0, #0
	bne	.L0
	movs	r0, #7
	b	.L1
	movs	r7, #0x10
	lsls	r0, r0, #0xc
.L0:
	movs	r0, #0
.L1:
	strb	r0, [r1]
	pop	{r0}
	bx	r0
	.size	sub_0804E014, . - sub_0804E014
