@ Generated by tools/gen_build.py. Do not edit.
@ Every byte of the ROM that has not been decompiled yet.

	.section .rom_00000000, "ax", %progbits
	.incbin "baserom.gba", 0x0, 0x1cd0

	.section .rom_00001cf0, "ax", %progbits
	.incbin "baserom.gba", 0x1cf0, 0x6e0

	.section .rom_000023ea, "ax", %progbits
	.incbin "baserom.gba", 0x23ea, 0x41a
	.globl sub_08002804
	.thumb_func
sub_08002804:
	.incbin "baserom.gba", 0x2804, 0x1158

	.section .rom_0000397c, "ax", %progbits
	.incbin "baserom.gba", 0x397c, 0x21dc
	.globl sub_08005B58
	.thumb_func
sub_08005B58:
	.incbin "baserom.gba", 0x5b58, 0x58

	.section .rom_00005bc2, "ax", %progbits
	.incbin "baserom.gba", 0x5bc2, 0xf1a

	.section .rom_00006b12, "ax", %progbits
	.incbin "baserom.gba", 0x6b12, 0x8a

	.section .rom_00006bb4, "ax", %progbits
	.incbin "baserom.gba", 0x6bb4, 0x2c

	.section .rom_00006c02, "ax", %progbits
	.incbin "baserom.gba", 0x6c02, 0x3ca
	.globl sub_08006FCC
	.thumb_func
sub_08006FCC:
	.incbin "baserom.gba", 0x6fcc, 0x1a4

	.section .rom_0000717c, "ax", %progbits
	.incbin "baserom.gba", 0x717c, 0x704

	.section .rom_00007892, "ax", %progbits
	.incbin "baserom.gba", 0x7892, 0x2

	.section .rom_000078a8, "ax", %progbits
	.incbin "baserom.gba", 0x78a8, 0x20fc

	.section .rom_000099c4, "ax", %progbits
	.incbin "baserom.gba", 0x99c4, 0x660

	.section .rom_0000a040, "ax", %progbits
	.incbin "baserom.gba", 0xa040, 0x1bc8

	.section .rom_0000bc28, "ax", %progbits
	.incbin "baserom.gba", 0xbc28, 0x154

	.section .rom_0000bd8e, "ax", %progbits
	.incbin "baserom.gba", 0xbd8e, 0x3ba

	.section .rom_0000c15a, "ax", %progbits
	.incbin "baserom.gba", 0xc15a, 0x4ba

	.section .rom_0000c628, "ax", %progbits
	.incbin "baserom.gba", 0xc628, 0x49c8

	.section .rom_00011002, "ax", %progbits
	.incbin "baserom.gba", 0x11002, 0x12

	.section .rom_0001102e, "ax", %progbits
	.incbin "baserom.gba", 0x1102e, 0x12

	.section .rom_00011056, "ax", %progbits
	.incbin "baserom.gba", 0x11056, 0x27e

	.section .rom_000112e8, "ax", %progbits
	.incbin "baserom.gba", 0x112e8, 0x207c

	.section .rom_00013380, "ax", %progbits
	.incbin "baserom.gba", 0x13380, 0x72c

	.section .rom_00013acc, "ax", %progbits
	.incbin "baserom.gba", 0x13acc, 0x3298
	.globl sub_08016D64
	.thumb_func
sub_08016D64:
	.incbin "baserom.gba", 0x16d64, 0x7a4

	.section .rom_00017514, "ax", %progbits
	.incbin "baserom.gba", 0x17514, 0x5b0

	.section .rom_00017ad8, "ax", %progbits
	.incbin "baserom.gba", 0x17ad8, 0x78

	.section .rom_00017b66, "ax", %progbits
	.incbin "baserom.gba", 0x17b66, 0x90a

	.section .rom_00018484, "ax", %progbits
	.incbin "baserom.gba", 0x18484, 0x810

	.section .rom_00018cb6, "ax", %progbits
	.incbin "baserom.gba", 0x18cb6, 0x2066

	.section .rom_0001ad38, "ax", %progbits
	.incbin "baserom.gba", 0x1ad38, 0x1d40

	.section .rom_0001ca98, "ax", %progbits
	.incbin "baserom.gba", 0x1ca98, 0x51a4

	.section .rom_00021c5c, "ax", %progbits
	.incbin "baserom.gba", 0x21c5c, 0x1cc
	.globl sub_08021E28
	.thumb_func
sub_08021E28:
	.incbin "baserom.gba", 0x21e28, 0x14
	.globl sub_08021E3C
	.thumb_func
sub_08021E3C:
	.incbin "baserom.gba", 0x21e3c, 0x1f0

	.section .rom_00022044, "ax", %progbits
	.incbin "baserom.gba", 0x22044, 0x7fc
	.globl sub_08022840
	.thumb_func
sub_08022840:
	.incbin "baserom.gba", 0x22840, 0x14
	.globl sub_08022854
	.thumb_func
sub_08022854:
	.incbin "baserom.gba", 0x22854, 0x2268

	.section .rom_00024ad6, "ax", %progbits
	.incbin "baserom.gba", 0x24ad6, 0x27cb2

	.section .rom_0004c7a0, "ax", %progbits
	.incbin "baserom.gba", 0x4c7a0, 0x1874

	.section .rom_0004e030, "ax", %progbits
	.incbin "baserom.gba", 0x4e030, 0xef0c

	.section .rom_0005cf5c, "ax", %progbits
	.incbin "baserom.gba", 0x5cf5c, 0xb8b4

	.section .rom_0006881e, "ax", %progbits
	.incbin "baserom.gba", 0x6881e, 0x29866

	.section .rom_0009209a, "ax", %progbits
	.incbin "baserom.gba", 0x9209a, 0x78a2

	.section .rom_0009995c, "ax", %progbits
	.incbin "baserom.gba", 0x9995c, 0x8e8

	.section .rom_0009a27c, "ax", %progbits
	.incbin "baserom.gba", 0x9a27c, 0x2b4

	.section .rom_0009a548, "ax", %progbits
	.incbin "baserom.gba", 0x9a548, 0x78

	.section .rom_0009a5e0, "ax", %progbits
	.incbin "baserom.gba", 0x9a5e0, 0xe22c
	.globl sub_080A880C
	.thumb_func
sub_080A880C:
	.incbin "baserom.gba", 0xa880c, 0x4

	.section .rom_000a8830, "ax", %progbits
	.incbin "baserom.gba", 0xa8830, 0x588
	.globl sub_080A8DB8
	.thumb_func
sub_080A8DB8:
	.incbin "baserom.gba", 0xa8db8, 0x6b4

	.section .rom_000a9476, "ax", %progbits
	.incbin "baserom.gba", 0xa9476, 0x11386

	.section .rom_000ba816, "ax", %progbits
	.incbin "baserom.gba", 0xba816, 0x6bb2
	.globl sub_080C13C8
	.thumb_func
sub_080C13C8:
	.incbin "baserom.gba", 0xc13c8, 0x1ef8

	.section .rom_000c47a8, "ax", %progbits
	.incbin "baserom.gba", 0xc47a8, 0x3360

	.section .rom_000c7b1e, "ax", %progbits
	.incbin "baserom.gba", 0xc7b1e, 0xd6

	.section .rom_000c7c12, "ax", %progbits
	.incbin "baserom.gba", 0xc7c12, 0x292
	.globl UnitStat
	.thumb_func
UnitStat:
	.incbin "baserom.gba", 0xc7ea4, 0x2d8

	.section .rom_000c8192, "ax", %progbits
	.incbin "baserom.gba", 0xc8192, 0x2

	.section .rom_000c81ae, "ax", %progbits
	.incbin "baserom.gba", 0xc81ae, 0x7a

	.section .rom_000c823e, "ax", %progbits
	.incbin "baserom.gba", 0xc823e, 0x2

	.section .rom_000c825e, "ax", %progbits
	.incbin "baserom.gba", 0xc825e, 0x2

	.section .rom_000c827e, "ax", %progbits
	.incbin "baserom.gba", 0xc827e, 0x2

	.section .rom_000c8296, "ax", %progbits
	.incbin "baserom.gba", 0xc8296, 0x2

	.section .rom_000c82b6, "ax", %progbits
	.incbin "baserom.gba", 0xc82b6, 0x2

	.section .rom_000c82d6, "ax", %progbits
	.incbin "baserom.gba", 0xc82d6, 0x2

	.section .rom_000c82f4, "ax", %progbits
	.incbin "baserom.gba", 0xc82f4, 0x1c

	.section .rom_000c8382, "ax", %progbits
	.incbin "baserom.gba", 0xc8382, 0x2

	.section .rom_000c83a4, "ax", %progbits
	.incbin "baserom.gba", 0xc83a4, 0x2400
	.globl sub_080CA7A4
	.thumb_func
sub_080CA7A4:
	.incbin "baserom.gba", 0xca7a4, 0xd00

	.section .rom_000cb4c0, "ax", %progbits
	.incbin "baserom.gba", 0xcb4c0, 0x1890
	.globl AbilityProp
	.thumb_func
AbilityProp:
	.incbin "baserom.gba", 0xccd50, 0x7f4

	.section .rom_000cd55e, "ax", %progbits
	.incbin "baserom.gba", 0xcd55e, 0x2

	.section .rom_000cd582, "ax", %progbits
	.incbin "baserom.gba", 0xcd582, 0x332

	.section .rom_000cdd04, "ax", %progbits
	.incbin "baserom.gba", 0xcdd04, 0x18

	.section .rom_000cdd3e, "ax", %progbits
	.incbin "baserom.gba", 0xcdd3e, 0x2

	.section .rom_000cdd62, "ax", %progbits
	.incbin "baserom.gba", 0xcdd62, 0x2

	.section .rom_000cdd86, "ax", %progbits
	.incbin "baserom.gba", 0xcdd86, 0x2

	.section .rom_000cddaa, "ax", %progbits
	.incbin "baserom.gba", 0xcddaa, 0x2

	.section .rom_000cddce, "ax", %progbits
	.incbin "baserom.gba", 0xcddce, 0x2

	.section .rom_000cddf2, "ax", %progbits
	.incbin "baserom.gba", 0xcddf2, 0x2

	.section .rom_000cde36, "ax", %progbits
	.incbin "baserom.gba", 0xcde36, 0x2

	.section .rom_000cde5a, "ax", %progbits
	.incbin "baserom.gba", 0xcde5a, 0x2

	.section .rom_000cde7e, "ax", %progbits
	.incbin "baserom.gba", 0xcde7e, 0x2

	.section .rom_000cdea2, "ax", %progbits
	.incbin "baserom.gba", 0xcdea2, 0x2

	.section .rom_000cdec6, "ax", %progbits
	.incbin "baserom.gba", 0xcdec6, 0x2

	.section .rom_000cdeea, "ax", %progbits
	.incbin "baserom.gba", 0xcdeea, 0x2

	.section .rom_000cdf0e, "ax", %progbits
	.incbin "baserom.gba", 0xcdf0e, 0x2

	.section .rom_000cdf52, "ax", %progbits
	.incbin "baserom.gba", 0xcdf52, 0x2

	.section .rom_000cdf76, "ax", %progbits
	.incbin "baserom.gba", 0xcdf76, 0x2

	.section .rom_000cdf9a, "ax", %progbits
	.incbin "baserom.gba", 0xcdf9a, 0x2

	.section .rom_000cdfbe, "ax", %progbits
	.incbin "baserom.gba", 0xcdfbe, 0x2

	.section .rom_000cdfe2, "ax", %progbits
	.incbin "baserom.gba", 0xcdfe2, 0x2

	.section .rom_000ce006, "ax", %progbits
	.incbin "baserom.gba", 0xce006, 0x2

	.section .rom_000ce02a, "ax", %progbits
	.incbin "baserom.gba", 0xce02a, 0x2

	.section .rom_000ce04e, "ax", %progbits
	.incbin "baserom.gba", 0xce04e, 0x2

	.section .rom_000ce092, "ax", %progbits
	.incbin "baserom.gba", 0xce092, 0x2

	.section .rom_000ce0b6, "ax", %progbits
	.incbin "baserom.gba", 0xce0b6, 0x2

	.section .rom_000ce0da, "ax", %progbits
	.incbin "baserom.gba", 0xce0da, 0x2

	.section .rom_000ce0fe, "ax", %progbits
	.incbin "baserom.gba", 0xce0fe, 0x2

	.section .rom_000ce122, "ax", %progbits
	.incbin "baserom.gba", 0xce122, 0x2

	.section .rom_000ce146, "ax", %progbits
	.incbin "baserom.gba", 0xce146, 0x2

	.section .rom_000ce16a, "ax", %progbits
	.incbin "baserom.gba", 0xce16a, 0x2

	.section .rom_000ce1ae, "ax", %progbits
	.incbin "baserom.gba", 0xce1ae, 0x2

	.section .rom_000ce1d2, "ax", %progbits
	.incbin "baserom.gba", 0xce1d2, 0x2

	.section .rom_000ce1f6, "ax", %progbits
	.incbin "baserom.gba", 0xce1f6, 0x2

	.section .rom_000ce21a, "ax", %progbits
	.incbin "baserom.gba", 0xce21a, 0x2

	.section .rom_000ce23e, "ax", %progbits
	.incbin "baserom.gba", 0xce23e, 0x2

	.section .rom_000ce262, "ax", %progbits
	.incbin "baserom.gba", 0xce262, 0x2

	.section .rom_000ce2a6, "ax", %progbits
	.incbin "baserom.gba", 0xce2a6, 0x2

	.section .rom_000ce2ca, "ax", %progbits
	.incbin "baserom.gba", 0xce2ca, 0x2

	.section .rom_000ce2ee, "ax", %progbits
	.incbin "baserom.gba", 0xce2ee, 0x2

	.section .rom_000ce312, "ax", %progbits
	.incbin "baserom.gba", 0xce312, 0x2

	.section .rom_000ce336, "ax", %progbits
	.incbin "baserom.gba", 0xce336, 0x4a

	.section .rom_000ce3a0, "ax", %progbits
	.incbin "baserom.gba", 0xce3a0, 0x63c8

	.section .rom_000d4772, "ax", %progbits
	.incbin "baserom.gba", 0xd4772, 0x53e6

	.section .rom_000d9b62, "ax", %progbits
	.incbin "baserom.gba", 0xd9b62, 0x1eee

	.section .rom_000dba5a, "ax", %progbits
	.incbin "baserom.gba", 0xdba5a, 0x302

	.section .rom_000dbd70, "ax", %progbits
	.incbin "baserom.gba", 0xdbd70, 0x144

	.section .rom_000dbed4, "ax", %progbits
	.incbin "baserom.gba", 0xdbed4, 0x15a8

	.section .rom_000dd488, "ax", %progbits
	.incbin "baserom.gba", 0xdd488, 0x3c

	.section .rom_000dd4d4, "ax", %progbits
	.incbin "baserom.gba", 0xdd4d4, 0xc4

	.section .rom_000dd5a6, "ax", %progbits
	.incbin "baserom.gba", 0xdd5a6, 0x30ea

	.section .rom_000e06a4, "ax", %progbits
	.incbin "baserom.gba", 0xe06a4, 0x4ae3c

	.section .rom_0012b502, "ax", %progbits
	.incbin "baserom.gba", 0x12b502, 0x2e66
	.globl sub_0812E368
	.thumb_func
sub_0812E368:
	.incbin "baserom.gba", 0x12e368, 0x18c
	.globl sub_0812E4F4
	.thumb_func
sub_0812E4F4:
	.incbin "baserom.gba", 0x12e4f4, 0x68
	.globl sub_0812E55C
	.thumb_func
sub_0812E55C:
	.incbin "baserom.gba", 0x12e55c, 0x148
	.globl sub_0812E6A4
	.thumb_func
sub_0812E6A4:
	.incbin "baserom.gba", 0x12e6a4, 0x6f4
	.globl AbilityMpCost
	.thumb_func
AbilityMpCost:
	.incbin "baserom.gba", 0x12ed98, 0x100
	.globl sub_0812EE98
	.thumb_func
sub_0812EE98:
	.incbin "baserom.gba", 0x12ee98, 0x38
	.globl sub_0812EED0
	.thumb_func
sub_0812EED0:
	.incbin "baserom.gba", 0x12eed0, 0x1fc

	.section .rom_0012f0d6, "ax", %progbits
	.incbin "baserom.gba", 0x12f0d6, 0x2

	.section .rom_0012f0e2, "ax", %progbits
	.incbin "baserom.gba", 0x12f0e2, 0x2
	.globl sub_0812F0E4
	.thumb_func
sub_0812F0E4:
	.incbin "baserom.gba", 0x12f0e4, 0x70
	.globl sub_0812F154
	.thumb_func
sub_0812F154:
	.incbin "baserom.gba", 0x12f154, 0x88
	.globl sub_0812F1DC
	.thumb_func
sub_0812F1DC:
	.incbin "baserom.gba", 0x12f1dc, 0x1e54
	.globl sub_08131030
	.thumb_func
sub_08131030:
	.incbin "baserom.gba", 0x131030, 0x2a28
	.globl sub_08133A58
	.thumb_func
sub_08133A58:
	.incbin "baserom.gba", 0x133a58, 0x15c
	.globl sub_08133BB4
	.thumb_func
sub_08133BB4:
	.incbin "baserom.gba", 0x133bb4, 0x608
	.globl sub_081341BC
	.thumb_func
sub_081341BC:
	.incbin "baserom.gba", 0x1341bc, 0xec
	.globl sub_081342A8
	.thumb_func
sub_081342A8:
	.incbin "baserom.gba", 0x1342a8, 0xc
	.globl sub_081342B4
	.thumb_func
sub_081342B4:
	.incbin "baserom.gba", 0x1342b4, 0xc
	.globl sub_081342C0
	.thumb_func
sub_081342C0:
	.incbin "baserom.gba", 0x1342c0, 0xdf90
	.globl sub_08142250
	.thumb_func
sub_08142250:
	.incbin "baserom.gba", 0x142250, 0x700
	.globl sub_08142950
	.thumb_func
sub_08142950:
	.incbin "baserom.gba", 0x142950, 0x160
	.globl sub_08142AB0
	.thumb_func
sub_08142AB0:
	.incbin "baserom.gba", 0x142ab0, 0x5b24

	.section .rom_001485e6, "ax", %progbits
	.incbin "baserom.gba", 0x1485e6, 0xd82

	.section .rom_00149384, "ax", %progbits
	.incbin "baserom.gba", 0x149384, 0xeb6c7c

