@ Generated by tools/gen_build.py. Do not edit.
@ Every byte of the ROM that has not been decompiled yet.

	.section .rom_00000000, "ax", %progbits
	.incbin "baserom.gba", 0x0, 0x23d0

	.section .rom_000023ea, "ax", %progbits
	.incbin "baserom.gba", 0x23ea, 0x37c6

	.section .rom_00005bc2, "ax", %progbits
	.incbin "baserom.gba", 0x5bc2, 0xf1a

	.section .rom_00006b12, "ax", %progbits
	.incbin "baserom.gba", 0x6b12, 0x8a

	.section .rom_00006bb4, "ax", %progbits
	.incbin "baserom.gba", 0x6bb4, 0xccc

	.section .rom_00007892, "ax", %progbits
	.incbin "baserom.gba", 0x7892, 0x2

	.section .rom_000078a8, "ax", %progbits
	.incbin "baserom.gba", 0x78a8, 0x20fc

	.section .rom_000099c4, "ax", %progbits
	.incbin "baserom.gba", 0x99c4, 0x660

	.section .rom_0000a040, "ax", %progbits
	.incbin "baserom.gba", 0xa040, 0x1bc8

	.section .rom_0000bc28, "ax", %progbits
	.incbin "baserom.gba", 0xbc28, 0x154

	.section .rom_0000bd8e, "ax", %progbits
	.incbin "baserom.gba", 0xbd8e, 0x3ba

	.section .rom_0000c15a, "ax", %progbits
	.incbin "baserom.gba", 0xc15a, 0x4ba

	.section .rom_0000c628, "ax", %progbits
	.incbin "baserom.gba", 0xc628, 0x49c8

	.section .rom_00011002, "ax", %progbits
	.incbin "baserom.gba", 0x11002, 0x12

	.section .rom_0001102e, "ax", %progbits
	.incbin "baserom.gba", 0x1102e, 0x12

	.section .rom_00011056, "ax", %progbits
	.incbin "baserom.gba", 0x11056, 0x27e

	.section .rom_000112e8, "ax", %progbits
	.incbin "baserom.gba", 0x112e8, 0x207c

	.section .rom_00013380, "ax", %progbits
	.incbin "baserom.gba", 0x13380, 0x72c

	.section .rom_00013acc, "ax", %progbits
	.incbin "baserom.gba", 0x13acc, 0x3ff8

	.section .rom_00017ad8, "ax", %progbits
	.incbin "baserom.gba", 0x17ad8, 0x78

	.section .rom_00017b66, "ax", %progbits
	.incbin "baserom.gba", 0x17b66, 0x90a

	.section .rom_00018484, "ax", %progbits
	.incbin "baserom.gba", 0x18484, 0x2898

	.section .rom_0001ad38, "ax", %progbits
	.incbin "baserom.gba", 0x1ad38, 0x1d40

	.section .rom_0001ca98, "ax", %progbits
	.incbin "baserom.gba", 0x1ca98, 0x5594

	.section .rom_00022044, "ax", %progbits
	.incbin "baserom.gba", 0x22044, 0x2a78

	.section .rom_00024ad6, "ax", %progbits
	.incbin "baserom.gba", 0x24ad6, 0x27cb2

	.section .rom_0004c7a0, "ax", %progbits
	.incbin "baserom.gba", 0x4c7a0, 0x1c070

	.section .rom_0006881e, "ax", %progbits
	.incbin "baserom.gba", 0x6881e, 0x29866

	.section .rom_0009209a, "ax", %progbits
	.incbin "baserom.gba", 0x9209a, 0x81aa

	.section .rom_0009a27c, "ax", %progbits
	.incbin "baserom.gba", 0x9a27c, 0xe594

	.section .rom_000a8830, "ax", %progbits
	.incbin "baserom.gba", 0xa8830, 0x11fcc

	.section .rom_000ba816, "ax", %progbits
	.incbin "baserom.gba", 0xba816, 0xd2f2

	.section .rom_000c7b1e, "ax", %progbits
	.incbin "baserom.gba", 0xc7b1e, 0xd6

	.section .rom_000c7c12, "ax", %progbits
	.incbin "baserom.gba", 0xc7c12, 0x56a

	.section .rom_000c8192, "ax", %progbits
	.incbin "baserom.gba", 0xc8192, 0x2

	.section .rom_000c81ae, "ax", %progbits
	.incbin "baserom.gba", 0xc81ae, 0x7a

	.section .rom_000c823e, "ax", %progbits
	.incbin "baserom.gba", 0xc823e, 0x2

	.section .rom_000c825e, "ax", %progbits
	.incbin "baserom.gba", 0xc825e, 0x2

	.section .rom_000c827e, "ax", %progbits
	.incbin "baserom.gba", 0xc827e, 0x2

	.section .rom_000c8296, "ax", %progbits
	.incbin "baserom.gba", 0xc8296, 0x2

	.section .rom_000c82b6, "ax", %progbits
	.incbin "baserom.gba", 0xc82b6, 0x2

	.section .rom_000c82d6, "ax", %progbits
	.incbin "baserom.gba", 0xc82d6, 0x2

	.section .rom_000c82f4, "ax", %progbits
	.incbin "baserom.gba", 0xc82f4, 0x1c

	.section .rom_000c8382, "ax", %progbits
	.incbin "baserom.gba", 0xc8382, 0x2

	.section .rom_000c83a4, "ax", %progbits
	.incbin "baserom.gba", 0xc83a4, 0x3100

	.section .rom_000cb4c0, "ax", %progbits
	.incbin "baserom.gba", 0xcb4c0, 0x2084

	.section .rom_000cd55e, "ax", %progbits
	.incbin "baserom.gba", 0xcd55e, 0x356

	.section .rom_000cdd04, "ax", %progbits
	.incbin "baserom.gba", 0xcdd04, 0x18

	.section .rom_000cdd3e, "ax", %progbits
	.incbin "baserom.gba", 0xcdd3e, 0x2

	.section .rom_000cdd62, "ax", %progbits
	.incbin "baserom.gba", 0xcdd62, 0x2

	.section .rom_000cdd86, "ax", %progbits
	.incbin "baserom.gba", 0xcdd86, 0x2

	.section .rom_000cddaa, "ax", %progbits
	.incbin "baserom.gba", 0xcddaa, 0x2

	.section .rom_000cddce, "ax", %progbits
	.incbin "baserom.gba", 0xcddce, 0x2

	.section .rom_000cddf2, "ax", %progbits
	.incbin "baserom.gba", 0xcddf2, 0x2

	.section .rom_000cde36, "ax", %progbits
	.incbin "baserom.gba", 0xcde36, 0x2

	.section .rom_000cde5a, "ax", %progbits
	.incbin "baserom.gba", 0xcde5a, 0x2

	.section .rom_000cde7e, "ax", %progbits
	.incbin "baserom.gba", 0xcde7e, 0x2

	.section .rom_000cdea2, "ax", %progbits
	.incbin "baserom.gba", 0xcdea2, 0x2

	.section .rom_000cdec6, "ax", %progbits
	.incbin "baserom.gba", 0xcdec6, 0x2

	.section .rom_000cdeea, "ax", %progbits
	.incbin "baserom.gba", 0xcdeea, 0x2

	.section .rom_000cdf0e, "ax", %progbits
	.incbin "baserom.gba", 0xcdf0e, 0x2

	.section .rom_000cdf52, "ax", %progbits
	.incbin "baserom.gba", 0xcdf52, 0x2

	.section .rom_000cdf76, "ax", %progbits
	.incbin "baserom.gba", 0xcdf76, 0x2

	.section .rom_000cdf9a, "ax", %progbits
	.incbin "baserom.gba", 0xcdf9a, 0x2

	.section .rom_000cdfbe, "ax", %progbits
	.incbin "baserom.gba", 0xcdfbe, 0x2

	.section .rom_000cdfe2, "ax", %progbits
	.incbin "baserom.gba", 0xcdfe2, 0x2

	.section .rom_000ce006, "ax", %progbits
	.incbin "baserom.gba", 0xce006, 0x2

	.section .rom_000ce02a, "ax", %progbits
	.incbin "baserom.gba", 0xce02a, 0x2

	.section .rom_000ce04e, "ax", %progbits
	.incbin "baserom.gba", 0xce04e, 0x2

	.section .rom_000ce092, "ax", %progbits
	.incbin "baserom.gba", 0xce092, 0x2

	.section .rom_000ce0b6, "ax", %progbits
	.incbin "baserom.gba", 0xce0b6, 0x2

	.section .rom_000ce0da, "ax", %progbits
	.incbin "baserom.gba", 0xce0da, 0x2

	.section .rom_000ce0fe, "ax", %progbits
	.incbin "baserom.gba", 0xce0fe, 0x2

	.section .rom_000ce122, "ax", %progbits
	.incbin "baserom.gba", 0xce122, 0x2

	.section .rom_000ce146, "ax", %progbits
	.incbin "baserom.gba", 0xce146, 0x2

	.section .rom_000ce16a, "ax", %progbits
	.incbin "baserom.gba", 0xce16a, 0x2

	.section .rom_000ce1ae, "ax", %progbits
	.incbin "baserom.gba", 0xce1ae, 0x2

	.section .rom_000ce1d2, "ax", %progbits
	.incbin "baserom.gba", 0xce1d2, 0x2

	.section .rom_000ce1f6, "ax", %progbits
	.incbin "baserom.gba", 0xce1f6, 0x2

	.section .rom_000ce21a, "ax", %progbits
	.incbin "baserom.gba", 0xce21a, 0x2

	.section .rom_000ce23e, "ax", %progbits
	.incbin "baserom.gba", 0xce23e, 0x2

	.section .rom_000ce262, "ax", %progbits
	.incbin "baserom.gba", 0xce262, 0x2

	.section .rom_000ce2a6, "ax", %progbits
	.incbin "baserom.gba", 0xce2a6, 0x2

	.section .rom_000ce2ca, "ax", %progbits
	.incbin "baserom.gba", 0xce2ca, 0x2

	.section .rom_000ce2ee, "ax", %progbits
	.incbin "baserom.gba", 0xce2ee, 0x2

	.section .rom_000ce312, "ax", %progbits
	.incbin "baserom.gba", 0xce312, 0x2

	.section .rom_000ce336, "ax", %progbits
	.incbin "baserom.gba", 0xce336, 0x4a

	.section .rom_000ce3a0, "ax", %progbits
	.incbin "baserom.gba", 0xce3a0, 0xd9bc

	.section .rom_000dbd70, "ax", %progbits
	.incbin "baserom.gba", 0xdbd70, 0x1754

	.section .rom_000dd4d4, "ax", %progbits
	.incbin "baserom.gba", 0xdd4d4, 0xc4

	.section .rom_000dd5a6, "ax", %progbits
	.incbin "baserom.gba", 0xdd5a6, 0x30ea

	.section .rom_000e06a4, "ax", %progbits
	.incbin "baserom.gba", 0xe06a4, 0x67f30

	.section .rom_001485e6, "ax", %progbits
	.incbin "baserom.gba", 0x1485e6, 0xd82

	.section .rom_00149384, "ax", %progbits
	.incbin "baserom.gba", 0x149384, 0xeb6c7c

