@ sub_080DD580, verbatim from the base ROM at 0x080dd580 (24 bytes).
@ Generated by tools/make_permuter_dir.py. Verify with tools/permuter_setup.sh.
@ prelude.inc is MIPS-only and is deliberately not included.

	.text
	.syntax unified
	.thumb
	.align 2, 0
	.globl sub_080DD580
	.type sub_080DD580, %function
	.thumb_func
sub_080DD580:
	push	{lr}
	ldrh	r0, [r0, #0xc]
	lsrs	r0, r0, #7
	movs	r1, #1
	movs	r2, #0
	ands	r0, r1
	cmp	r0, #1
	bne	.L0
	movs	r2, #1
.L0:
	adds	r0, r2, #0
	pop	{r1}
	bx	r1
	.size	sub_080DD580, . - sub_080DD580
