@ sub_08092084, verbatim from the base ROM at 0x08092084 (22 bytes).
@ Generated by tools/make_permuter_dir.py. Verify with tools/permuter_setup.sh.
@ prelude.inc is MIPS-only and is deliberately not included.

	.text
	.syntax unified
	.thumb
	.align 2, 0
	.globl sub_08092084
	.type sub_08092084, %function
	.thumb_func
sub_08092084:
	push	{r4, lr}
	lsls	r1, r1, #0x10
	asrs	r1, r1, #0xf
	adds	r4, r0, r1
	strb	r2, [r4]
	adds	r0, #1
	adds	r0, r0, r1
	strb	r3, [r0]
	pop	{r4}
	pop	{r0}
	bx	r0
	.size	sub_08092084, . - sub_08092084
