@ sub_080C8240, verbatim from the base ROM at 0x080c8240 (30 bytes).
@ Generated by tools/make_permuter_dir.py. Verify with tools/permuter_setup.sh.
@ prelude.inc is MIPS-only and is deliberately not included.

	.text
	.syntax unified
	.thumb
	.align 2, 0
	.globl sub_080C8240
	.type sub_080C8240, %function
	.thumb_func
sub_080C8240:
	push	{lr}
	movs	r1, #0
	cmp	r0, #0
	beq	.L0
	ldrh	r1, [r0, #0x28]
	movs	r0, #0x80
	lsls	r0, r0, #8
	ands	r0, r1
	lsls	r0, r0, #0x10
	lsrs	r0, r0, #0x10
	rsbs	r0, r0, #0
	lsrs	r1, r0, #0x1f
.L0:
	adds	r0, r1, #0
	pop	{r1}
	bx	r1
	.size	sub_080C8240, . - sub_080C8240
