@ sub_080BDC20, verbatim from the base ROM at 0x080bdc20 (34 bytes).
@ Generated by tools/make_permuter_dir.py. Verify with tools/permuter_setup.sh.
@ prelude.inc is MIPS-only and is deliberately not included.

	.text
	.syntax unified
	.thumb
	.align 2, 0
	.globl sub_080BDC20
	.type sub_080BDC20, %function
	.thumb_func
sub_080BDC20:
	push	{lr}
	lsls	r1, r1, #0x18
	lsls	r2, r2, #0x18
	lsrs	r1, r1, #0x16
	lsrs	r2, r2, #0x12
	adds	r1, r1, r2
	adds	r0, r0, r1
	ldr	r1, [r0]
	movs	r0, #1
	rsbs	r0, r0, #0
	cmp	r1, r0
	beq	.L0
	adds	r0, r1, #0
	b	.L1
.L0:
	movs	r0, #0
.L1:
	pop	{r1}
	bx	r1
	.size	sub_080BDC20, . - sub_080BDC20
