@ sub_08017B50, verbatim from the base ROM at 0x08017b50 (22 bytes).
@ Generated by tools/make_permuter_dir.py. Verify with tools/permuter_setup.sh.
@ prelude.inc is MIPS-only and is deliberately not included.

	.text
	.syntax unified
	.thumb
	.align 2, 0
	.globl sub_08017B50
	.type sub_08017B50, %function
	.thumb_func
sub_08017B50:
	push	{lr}
	movs	r2, #0x18
	ldrsh	r1, [r0, r2]
	ldrb	r0, [r0, #0x16]
	cmp	r0, r1
	ble	.L0
	adds	r0, r1, #0
.L0:
	lsls	r0, r0, #0x10
	lsrs	r0, r0, #0x10
	pop	{r1}
	bx	r1
	.size	sub_08017B50, . - sub_08017B50
