@ sub_0800A024, verbatim from the base ROM at 0x0800a024 (28 bytes).
@ Generated by tools/make_permuter_dir.py. Verify with tools/permuter_setup.sh.
@ prelude.inc is MIPS-only and is deliberately not included.

	.text
	.syntax unified
	.thumb
	.align 2, 0
	.globl sub_0800A024
	.type sub_0800A024, %function
	.thumb_func
sub_0800A024:
	push	{lr}
	ldr	r2, [pc, #0x14]
	adds	r1, r2, #0
	adds	r1, #0xa2
	ldrh	r0, [r1]
	cmp	r0, #0
	bne	.L0
	adds	r0, r2, #0
	adds	r0, #0xa0
	ldrh	r0, [r0]
.L0:
	pop	{r1}
	bx	r1
	movs	r0, #0xd0
	lsls	r0, r0, #8
	.size	sub_0800A024, . - sub_0800A024
