"""Generate C for the large bitfield accessor clusters.

The ROM contains long runs of generated-looking flag accessors. Each cluster
shares an instruction shape and differs only in struct offset and bit mask, so
one template per shape plus operand extraction covers ~100 functions.

Usage:
    python tools/gen_bitfield.py build/leaf_candidates.json src/generated
"""
import os
import re
import sys
import json

# ---- shapes -----------------------------------------------------------------

GET_BYTE_BIT = "push|adds|movs|ldrb|ands|cmp|beq|movs|b|movs|pop|bx"
GET_BYTE_BIT_ALT = "push|movs|adds|ldrb|ands|cmp|beq|movs|b|movs|pop|bx"
SET_BYTE_BIT_NEG = ("push|lsls|adds|adds|movs|rsbs|ldrb|ands|strb|cmp|beq|"
                    "adds|movs|orrs|strb|pop|bx")
SET_BYTE_BIT_POS = ("push|lsls|adds|adds|ldrb|movs|ands|strb|cmp|beq|"
                    "adds|movs|orrs|strb|pop|bx")
GET_HW_BIT_SHIFT = "push|movs|cmp|beq|ldrh|movs|lsls|ands|lsls|lsrs|rsbs|lsrs|adds|pop|bx"
GET_HW_BIT = "push|movs|cmp|beq|ldrh|movs|ands|lsls|lsrs|rsbs|lsrs|adds|pop|bx"

IMM = re.compile(r"#(-?(?:0x)?[0-9a-fA-F]+)\s*$")
LDR_OFF = re.compile(r"\[\w+, #(0x[0-9a-fA-F]+|\d+)\]")


def imm_of(ins):
    m = IMM.search(ins["op_str"])
    return int(m.group(1), 0) if m else None


def by_mn(d, mn):
    return [i for i in d if i["mnemonic"] == mn]


# ---- templates --------------------------------------------------------------

HEADER = """\
/* {name} - {addr:#010x}, {size} bytes, {callers} callers.
 * Generated by tools/gen_bitfield.py. NOT YET MATCHING - see
 * docs/matching-notes.md for the outstanding branch-layout discrepancy.
 */

typedef unsigned char u8;
typedef unsigned short u16;

struct Obj
{{
    u8 filler_00[{off:#x}];
{field}
}};
"""

GETTER_BYTE = """
u8 {name}(struct Obj *obj)
{{
    if (obj->flags & {mask:#x})
        return 1;
    return 0;
}}
"""

SETTER_BYTE = """
void {name}(struct Obj *obj, u8 set)
{{
    obj->flags &= ~{mask:#x};
    if (set)
        obj->flags |= {mask:#x};
}}
"""

GETTER_HW = """
u8 {name}(struct Obj *obj)
{{
    if (obj == 0)
        return 0;
    return (obj->flags & {mask:#x}) != 0;
}}
"""


def gen(f):
    """Return C source for a known shape, or None."""
    d = f["disasm"]
    shape = f["shape"]

    if shape in (GET_BYTE_BIT, GET_BYTE_BIT_ALT):
        off = imm_of(by_mn(d, "adds")[0])
        mask = imm_of(by_mn(d, "movs")[0])
        if off is None or mask is None:
            return None
        body = GETTER_BYTE.format(name=f["name"], mask=mask)
        field = "    u8 flags;"

    elif shape in (SET_BYTE_BIT_NEG, SET_BYTE_BIT_POS):
        adds = by_mn(d, "adds")
        off = imm_of(adds[1])
        mask = imm_of(by_mn(d, "movs")[-1])
        if off is None or mask is None:
            return None
        body = SETTER_BYTE.format(name=f["name"], mask=mask)
        field = "    u8 flags;"

    elif shape in (GET_HW_BIT_SHIFT, GET_HW_BIT):
        ldrh = by_mn(d, "ldrh")[0]
        m = LDR_OFF.search(ldrh["op_str"])
        if not m:
            return None
        off = int(m.group(1), 0)
        mask = imm_of(by_mn(d, "movs")[1])
        if shape is GET_HW_BIT_SHIFT:
            mask <<= imm_of(by_mn(d, "lsls")[0])
        body = GETTER_HW.format(name=f["name"], mask=mask)
        field = "    u16 flags;"

    else:
        return None

    return HEADER.format(name=f["name"], addr=f["addr"], size=f["size"],
                         callers=f["callers"], off=off, field=field) + body


def main(argv):
    if len(argv) != 2:
        print(__doc__)
        return 2
    manifest, outdir = argv
    os.makedirs(outdir, exist_ok=True)

    funcs = json.load(open(manifest))
    written = 0
    skipped = 0
    for f in funcs:
        src = gen(f)
        if src is None:
            skipped += 1
            continue
        with open(os.path.join(outdir, f["name"] + ".c"), "w", newline="\n") as fh:
            fh.write(src)
        written += 1

    print(f"generated {written} C files in {outdir}  ({skipped} shapes not templated)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
