"""Generate C for the large bitfield accessor clusters.

The ROM contains long runs of generated-looking flag accessors. Each cluster
shares an instruction shape and differs only in struct offset and bit mask, so
one template per shape plus operand extraction covers ~100 functions.

Usage:
    python tools/gen_bitfield.py build/leaf_candidates.json src/generated
"""
import os
import re
import sys
import json

# ---- shapes -----------------------------------------------------------------

GET_BYTE_BIT = "push|adds|movs|ldrb|ands|cmp|beq|movs|b|movs|pop|bx"
GET_BYTE_BIT_ALT = "push|movs|adds|ldrb|ands|cmp|beq|movs|b|movs|pop|bx"
SET_BYTE_BIT_NEG = ("push|lsls|adds|adds|movs|rsbs|ldrb|ands|strb|cmp|beq|"
                    "adds|movs|orrs|strb|pop|bx")
SET_BYTE_BIT_POS = ("push|lsls|adds|adds|ldrb|movs|ands|strb|cmp|beq|"
                    "adds|movs|orrs|strb|pop|bx")
GET_HW_BIT_SHIFT = "push|movs|cmp|beq|ldrh|movs|lsls|ands|lsls|lsrs|rsbs|lsrs|adds|pop|bx"
GET_HW_BIT = "push|movs|cmp|beq|ldrh|movs|ands|lsls|lsrs|rsbs|lsrs|adds|pop|bx"

IMM = re.compile(r"#(-?(?:0x)?[0-9a-fA-F]+)\s*$")
LDR_OFF = re.compile(r"\[\w+, #(0x[0-9a-fA-F]+|\d+)\]")


def imm_of(ins):
    m = IMM.search(ins["op_str"])
    return int(m.group(1), 0) if m else None


def by_mn(d, mn):
    return [i for i in d if i["mnemonic"] == mn]


# ---- templates --------------------------------------------------------------

HEADER = """\
/* {name} - {addr:#010x}, {size} bytes, {callers} callers.
 * Generated by tools/gen_bitfield.py. NOT YET MATCHING - see
 * docs/matching-notes.md for the outstanding branch-layout discrepancy.
 */

typedef unsigned char u8;
typedef unsigned short u16;

struct Obj
{{
    u8 filler_00[{off:#x}];
{field}
}};
"""

# Spelling found by decomp-permuter and verified byte-exact. Three details all
# matter: the condition must be negated (else the branch layout mirrors), the
# field must be reached through a pointer temp, and the mask must be an int
# variable rather than a literal (else the mask and value swap registers).
GETTER_BYTE = """
u8 {name}(struct Obj *obj)
{{
    u8 *p = &obj->flags;
    int mask = {mask:#x};

    if (!(*p & mask))
        return 0;
    return 1;
}}
"""

# Found by decomp-permuter. The duplicated branch is load-bearing and not a
# transcription error: `p || notmask` is always true and both arms are
# identical, but removing them makes gcc materialise the mask before copying
# the cleared value, a 4-byte difference. Every clean spelling tried plateaus
# at 4 bytes off. Matching wins; see docs/matching-notes.md.
# Same as GETTER_BYTE with the two declarations swapped. The target sets up the
# mask before the pointer arithmetic, and declaration order drives that.
GETTER_BYTE_ALT = """
u8 {name}(struct Obj *obj)
{{
    int mask = {mask:#x};
    u8 *p = &obj->flags;

    if (!(*p & mask))
        return 0;
    return 1;
}}
"""

SETTER_BYTE = """
void {name}(struct Obj *obj, u8 set)
{{
    u8 *p = &obj->flags;
    int notmask = ~{mask:#x};
    int mask = {mask:#x};

    *p = *p & notmask;
    if (set)
    {{
        if (p || notmask)
            *p = (*p & notmask) | mask;
        else
            *p = (*p & notmask) | mask;
    }}
}}
"""

# Cluster C. The result-variable form plus an int mask and an explicit u16
# temp; a direct `return (obj->flags & MASK) != 0;` gets optimised into a
# single shift instead of the original's and / truncate / neg / lsr sequence.
GETTER_HW = """
u8 {name}(struct Obj *obj)
{{
    u8 r = 0;
    int mask = {mask:#x};
    u16 v;

    if (obj != 0)
    {{
        v = obj->flags & mask;
        r = v != 0;
    }}
    return r;
}}
"""


def gen(f):
    """Return C source for a known shape, or None."""
    d = f["disasm"]
    shape = f["shape"]

    # GET_BYTE_BIT_ALT (3 functions, mask setup before the pointer arithmetic)
    # and the GET_HW_BIT shapes (cluster C) are deliberately not generated:
    # the templates below get them to 4 and 21 bytes off respectively, and
    # emitting known-bad C into src/ would make the tree stop being all-matching.
    if shape == GET_BYTE_BIT:
        off = imm_of(by_mn(d, "adds")[0])
        mask = imm_of(by_mn(d, "movs")[0])
        if off is None or mask is None:
            return None
        body = GETTER_BYTE.format(name=f["name"], mask=mask)
        field = "    u8 flags;"

    elif shape == GET_BYTE_BIT_ALT:
        off = imm_of(by_mn(d, "adds")[0])
        mask = imm_of(by_mn(d, "movs")[0])
        if off is None or mask is None:
            return None
        body = GETTER_BYTE_ALT.format(name=f["name"], mask=mask)
        field = "    u8 flags;"

    elif shape in (SET_BYTE_BIT_NEG, SET_BYTE_BIT_POS):
        adds = by_mn(d, "adds")
        off = imm_of(adds[1])
        mask = imm_of(by_mn(d, "movs")[-1])
        if off is None or mask is None:
            return None
        body = SETTER_BYTE.format(name=f["name"], mask=mask)
        field = "    u8 flags;"

    elif shape in (GET_HW_BIT_SHIFT, GET_HW_BIT):
        ldrh = by_mn(d, "ldrh")[0]
        m = LDR_OFF.search(ldrh["op_str"])
        if not m:
            return None
        off = int(m.group(1), 0)
        mask = imm_of(by_mn(d, "movs")[1])
        if mask is None:
            return None
        if shape == GET_HW_BIT_SHIFT:
            mask <<= imm_of(by_mn(d, "lsls")[0])
        body = GETTER_HW.format(name=f["name"], mask=mask)
        field = "    u16 flags;"

    else:
        return None

    return HEADER.format(name=f["name"], addr=f["addr"], size=f["size"],
                         callers=f["callers"], off=off, field=field) + body


def main(argv):
    if len(argv) != 2:
        print(__doc__)
        return 2
    manifest, outdir = argv
    os.makedirs(outdir, exist_ok=True)

    funcs = json.load(open(manifest))
    written = 0
    skipped = 0
    for f in funcs:
        src = gen(f)
        if src is None:
            skipped += 1
            continue
        with open(os.path.join(outdir, f["name"] + ".c"), "w", newline="\n") as fh:
            fh.write(src)
        written += 1

    print(f"generated {written} C files in {outdir}  ({skipped} shapes not templated)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
