"""Build a decomp-permuter scratch directory for a function.

Generates target.s from the manifest disassembly, using unified Thumb syntax so
capstone's mnemonics can be emitted verbatim, and resolves branch targets to
local labels. Copies in base.c and compile.sh.

Always verify the result with tools/permuter_setup.sh before searching: a
target.s that assembles to the wrong bytes searches for the wrong function
without complaining.

Usage:
    python tools/make_permuter_dir.py <manifest.json> <func_name> <base.c> [outroot]
"""
import os
import re
import sys
import json
import shutil

BRANCHES = {"b", "beq", "bne", "bcs", "bhs", "bcc", "blo", "bmi", "bpl",
            "bvs", "bvc", "bhi", "bls", "bge", "blt", "bgt", "ble"}

TARGET_RE = re.compile(r"#(0x[0-9a-fA-F]+)")

HEADER = """\
@ {name}, verbatim from the base ROM at {addr:#010x} ({size} bytes).
@ Generated by tools/make_permuter_dir.py. Verify with tools/permuter_setup.sh.
@ prelude.inc is MIPS-only and is deliberately not included.

	.text
	.syntax unified
	.thumb
	.align 2, 0
	.globl {name}
	.type {name}, %function
	.thumb_func
{name}:
"""

SETTINGS = 'func_name = "{name}"\ncompiler_type = "gcc"\n'


def build_target_s(f):
    insns = f["disasm"]
    addrs = {i["addr"] for i in insns}

    # branch targets inside the function become local labels
    labels = {}
    for i in insns:
        if i["mnemonic"] in BRANCHES:
            m = TARGET_RE.search(i["op_str"])
            if not m:
                continue
            tgt = int(m.group(1), 0)
            if tgt in addrs:
                labels.setdefault(tgt, f".L{len(labels)}")

    out = [HEADER.format(name=f["name"], addr=f["addr"], size=f["size"])]
    for i in insns:
        if i["addr"] in labels:
            out.append(f"{labels[i['addr']]}:\n")
        mn, ops = i["mnemonic"], i["op_str"]
        if mn in BRANCHES:
            m = TARGET_RE.search(ops)
            if m:
                tgt = int(m.group(1), 0)
                if tgt in labels:
                    ops = labels[tgt]
        out.append(f"\t{mn}\t{ops}\n" if ops else f"\t{mn}\n")
    out.append(f"\t.size\t{f['name']}, . - {f['name']}\n")
    return "".join(out)


def main(argv):
    if len(argv) < 3:
        print(__doc__)
        return 2

    manifest, name, base_c = argv[0], argv[1], argv[2]
    outroot = argv[3] if len(argv) > 3 else "permuter"

    funcs = {f["name"]: f for f in json.load(open(manifest))}
    f = funcs.get(name)
    if f is None:
        print(f"error: {name} not in manifest")
        return 1

    d = os.path.join(outroot, name)
    os.makedirs(d, exist_ok=True)

    with open(os.path.join(d, "target.s"), "w", newline="\n") as fh:
        fh.write(build_target_s(f))
    shutil.copyfile(base_c, os.path.join(d, "base.c"))
    with open(os.path.join(d, "settings.toml"), "w", newline="\n") as fh:
        fh.write(SETTINGS.format(name=name))

    template = os.path.join(outroot, "sub_080CD92C", "compile.sh")
    if os.path.isfile(template):
        shutil.copyfile(template, os.path.join(d, "compile.sh"))

    print(f"created {d} ({f['size']} bytes, {f['callers']} callers)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
