"""Decomp.dev-style progress report, computed from this repo's own history.

    python tools/progress_history.py            # table over time + current totals
    python tools/progress_history.py --badge    # one-line markdown shield JSON
    python tools/progress_history.py --json     # machine-readable snapshots

The matched set is authoritative in data/functions.json at each commit, so the
history is exact rather than estimated: every commit that moved the index is a
data point, and the working tree is the newest one.

Discovered-function totals come from build/functions_all.json when present
(luvdis + local discovery, regenerated by tools/merge_luvdis.py). Without it
the report still works; it just says so instead of inventing a denominator.
"""

import argparse
import json
import os
import subprocess
import sys
from datetime import date

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX = os.path.join(REPO, "data", "functions.json")
DISCOVERED = os.path.join(REPO, "build", "functions_all.json")

# From the initial ROM survey; same denominator tools/progress.py uses.
CODE_REGION = 0x360000
ROM_SIZE = 0x1000000


def _sum_index(text):
    data = json.loads(text)
    funcs = data["functions"]
    return len(funcs), sum(f["size"] for f in funcs)


def snapshots():
    """(date, hash, count, bytes) for every commit that touched the index."""
    log = subprocess.run(
        ["git", "log", "--format=%h %ad", "--date=short", "--", "data/functions.json"],
        cwd=REPO, capture_output=True, text=True, check=True,
    )
    out = []
    for line in log.stdout.splitlines():
        rev, day = line.split()
        blob = subprocess.run(
            ["git", "show", f"{rev}:data/functions.json"],
            cwd=REPO, capture_output=True, text=True, check=True,
        ).stdout
        n, total = _sum_index(blob)
        out.append({"date": day, "commit": rev, "functions": n, "bytes": total})
    out.reverse()

    # The working tree, if it is ahead of the last commit.
    try:
        with open(INDEX) as fh:
            n, total = _sum_index(fh.read())
    except FileNotFoundError:
        return out
    last = out[-1] if out else {"functions": -1, "bytes": -1}
    if (n, total) != (last["functions"], last["bytes"]):
        out.append({"date": date.today().isoformat(), "commit": "worktree",
                    "functions": n, "bytes": total})
    return out


def _discovereds():
    try:
        with open(DISCOVERED) as fh:
            data = json.load(fh)
        funcs = data["functions"] if isinstance(data, dict) and "functions" in data else data
        return len(funcs), sum(f["size"] for f in funcs)
    except (FileNotFoundError, KeyError, TypeError):
        return None, None


def _velocity(snaps):
    """Byte rate over the last 30 days of history, in bytes/day."""
    from datetime import datetime, timedelta
    if not snaps:
        return 0.0
    now = datetime.strptime(snaps[-1]["date"], "%Y-%m-%d")
    window = [s for s in snaps
              if now - datetime.strptime(s["date"], "%Y-%m-%d") <= timedelta(days=30)]
    if not window:
        return 0.0
    elapsed = max((now - datetime.strptime(window[0]["date"], "%Y-%m-%d")).days, 1)
    return (snaps[-1]["bytes"] - snaps[0]["bytes"]) / elapsed


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--badge", action="store_true",
                   help="print a shields.io endpoint JSON instead of a table")
    p.add_argument("--json", action="store_true", help="print all snapshots as JSON")
    args = p.parse_args(argv)

    snaps = snapshots()
    n, total = snaps[-1]["functions"], snaps[-1]["bytes"]
    dn, db = _discovereds()

    if args.json:
        payload = {"snapshots": snaps,
                   "discovered": {"functions": dn, "bytes": db},
                   "code_region_bytes": CODE_REGION}
        json.dump(payload, sys.stdout, indent=2)
        print()
        return 0

    if args.badge:
        pct = 100.0 * total / db if db else None
        label = f"{pct:.2f}% of discovered bytes" if pct is not None \
            else f"{total:,} C bytes"
        json.dump({"schemaVersion": 1, "label": "FFTA decomp",
                   "message": label}, sys.stdout)
        print()
        return 0

    first, last = snaps[0], snaps[-1]
    days = max((date.fromisoformat(last["date"]) - date.fromisoformat(first["date"])).days, 1)

    print(f"FFTA decompilation progress - {last['date']} ({last['commit']})")
    print()
    print(f"  functions matched : {n} of "
          f"{dn if dn else '?'} discovered"
          + (f" ({100.0 * n / dn:.1f}%)" if dn else ""))
    line = f"  bytes as C        : {total:,}"
    if db:
        line += f" of {db:,}"
    print(line)
    if db:
        print(f"                      ({100.0 * total / db:.2f}% of discovered "
              f"code; {100.0 * total / CODE_REGION:.3f}% of the "
              f"{CODE_REGION // 1024} KiB code region)")
    print(f"  history           : {first['date']} -> {last['date']} "
          f"({days} days, {len(snaps)} indexed snapshots)")
    print(f"  velocity          : {_velocity(snaps):.0f} bytes/day over the "
          f"last 30 days of activity")
    if db:
        eta = (db - total) / _velocity(snaps)
        print(f"  linear forecast   : {eta:.0f} more days at that rate "
              f"(byte rate is a poor predictor; see docs/roadmap.md)")
    print()
    print("  date        commit    functions     C bytes")
    for s in snaps:
        print(f"  {s['date']}  {s['commit']:8}  {s['functions']:9}  "
              f"{s['bytes']:10,}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
