@ sub_08006B9C, verbatim from the base ROM at 0x08006b9c (24 bytes).
@ Generated by tools/make_permuter_dir.py. Verify with tools/permuter_setup.sh.
@ prelude.inc is MIPS-only and is deliberately not included.

	.text
	.syntax unified
	.thumb
	.align 2, 0
	.globl sub_08006B9C
	.type sub_08006B9C, %function
	.thumb_func
sub_08006B9C:
	push	{lr}
	adds	r1, r0, #0
	ldrb	r0, [r1, #3]
	cmp	r0, #0xff
	beq	.L0
	ldr	r1, [r1, #8]
	lsls	r0, r0, #2
	adds	r0, r0, r1
	movs	r1, #0
	str	r1, [r0]
.L0:
	pop	{r0}
	bx	r0
	.size	sub_08006B9C, . - sub_08006B9C
